export interface Style {
  name: string;
  value: string; // The value to be used in the prompt
  imageUrl: string;
  category: '4d' | '3d' | '2d' | 'anime' | 'roblox' | 'stickman' | 'fantasy';
}

export const styles: Style[] = [
  // --- 4D VIDEO STYLES (30 Styles) ---
  { name: 'Cinematic Realism 4D', category: '4d', value: '4D Cinematic Realism, ultra-real lighting, deep motion blur, film-like steady camera moves, 8k raw photo quality', imageUrl: 'https://images.pexels.com/photos/3035151/pexels-photo-3035151.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Ultra-Realistic Cinematic', category: '4d', value: '4D Ultra-Realistic Cinematic, masterwork lighting, high dynamic range, anamorphic lens flares, IMAX depth of field, incredible sharpness', imageUrl: 'https://images.pexels.com/photos/2526105/pexels-photo-2526105.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Futuristic Sci-Fi 4D', category: '4d', value: '4D Futuristic Sci-Fi, holograms, neon glitch, digital particles, cyber environments, immersive depth', imageUrl: 'https://images.pexels.com/photos/2526105/pexels-photo-2526105.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Anime 4D', category: '4d', value: '4D Anime Style, hand-drawn characters with cinematic 3D camera movement, dynamic depth effects, high-energy impact', imageUrl: 'https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Hyper-Real 4D', category: '4d', value: '4D Hyper-Realism, extreme skin texture detail, micro-movements, lifelike physics, octane render, macro focus', imageUrl: 'https://images.pexels.com/photos/7848995/pexels-photo-7848995.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Fantasy 4D', category: '4d', value: '4D Fantasy, magical glowing particles, floating islands, mythical creatures, epic sweeping motion, dreamlike', imageUrl: 'https://images.pexels.com/photos/289998/pexels-photo-289998.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Nature Immersion 4D', category: '4d', value: '4D Nature Immersion, wind effects, rain, thick fog, ocean spray, environmental motion focus, 8k photography', imageUrl: 'https://images.pexels.com/photos/3762299/pexels-photo-3762299.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Action / Combat 4D', category: '4d', value: '4D Action Combat, slow-motion impacts, heavy camera shake, flying debris, dramatic depth of field', imageUrl: 'https://images.pexels.com/photos/207529/pexels-photo-207529.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Luxury / Fashion 4D', category: '4d', value: '4D Luxury Fashion, smooth elegant motion, glossy textures, premium lighting, high-end editorial feel', imageUrl: 'https://images.pexels.com/photos/1036396/pexels-photo-1036396.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Horror / Dark 4D', category: '4d', value: '4D Horror, volumetric fog, deep shadows, sudden depth changes, intense eerie atmosphere, grainy thriller look', imageUrl: 'https://images.pexels.com/photos/5794711/pexels-photo-5794711.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Abstract / Art 4D', category: '4d', value: '4D Abstract Art, flowing liquid shapes, color morphing, surreal motion, artistic geometry, experimental lighting', imageUrl: 'https://images.pexels.com/photos/1193743/pexels-photo-1193743.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Epic Mythological 4D', category: '4d', value: '4D Epic Mythological, gods and monsters, divine light beams, ancient ruins, heroic scale, ethereal particles', imageUrl: 'https://images.pexels.com/photos/289998/pexels-photo-289998.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Bioluminescent Jungle 4D', category: '4d', value: '4D Bioluminescent Jungle, glowing flora and fauna, exotic bioluminescence, deep forest shadows, magical night atmosphere', imageUrl: 'https://images.pexels.com/photos/3762299/pexels-photo-3762299.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Steampunk Industrial 4D', category: '4d', value: '4D Steampunk Industrial, brass and copper gears, steam pipes, victorian mechanical engineering, warm lantern light, smoggy air', imageUrl: 'https://images.pexels.com/photos/2526105/pexels-photo-2526105.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Celestial Cosmic 4D', category: '4d', value: '4D Celestial Cosmic, nebula clouds, swirling galaxies, star clusters, celestial bodies in motion, cosmic dust', imageUrl: 'https://images.pexels.com/photos/207529/pexels-photo-207529.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Cyber-City Night 4D', category: '4d', value: '4D Cyber-City Night, high-speed traffic, digital rain, skyscraper neon lights, futuristic cityscape, verticality focus', imageUrl: 'https://images.pexels.com/photos/3035151/pexels-photo-3035151.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Frozen Tundra 4D', category: '4d', value: '4D Frozen Tundra, ice crystal shards, blizzard wind, cracked glaciers, cold blue lighting, extreme environment physics', imageUrl: 'https://images.pexels.com/photos/3762299/pexels-photo-3762299.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Volcanic Magma 4D', category: '4d', value: '4D Volcanic Magma, flowing lava rivers, falling ash, glowing embers, high-heat haze distortion, volcanic thunder', imageUrl: 'https://images.pexels.com/photos/207529/pexels-photo-207529.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Ancient Temple 4D', category: '4d', value: '4D Ancient Temple, stone carvings, dust motes in sunlight, vine-covered ruins, lost civilization atmosphere, mysterious depth', imageUrl: 'https://images.pexels.com/photos/289998/pexels-photo-289998.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Macro Bug World 4D', category: '4d', value: '4D Macro Bug World, giant insects, dew drops on grass, tiny life focus, extreme close-up perspectives, vibrant nature colors', imageUrl: 'https://images.pexels.com/photos/3762299/pexels-photo-3762299.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Neon Samurai 4D', category: '4d', value: '4D Neon Samurai, glowing katanas, futuristic armor, rain-slicked city streets, high-contrast action lighting', imageUrl: 'https://images.pexels.com/photos/2526105/pexels-photo-2526105.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Ocean Abyss 4D', category: '4d', value: '4D Ocean Abyss, bioluminescent creatures, deep pressure effects, glowing seafloor, murky blue depth, cinematic underwater movement', imageUrl: 'https://images.pexels.com/photos/3762299/pexels-photo-3762299.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Dragon Rider 4D', category: '4d', value: '4D Dragon Rider, flying through clouds, fire breath embers, realistic dragon scales, high-altitude wind effects, epic fantasy', imageUrl: 'https://images.pexels.com/photos/289998/pexels-photo-289998.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Crystal Forest 4D', category: '4d', value: '4D Crystal Forest, translucent trees, refracting light beams, magical aura, prismatic particles, sharp glassy textures', imageUrl: 'https://images.pexels.com/photos/1193743/pexels-photo-1193743.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Cyberpunk Rain 4D', category: '4d', value: '4D Cyberpunk Rain, heavy downpour, neon reflections on wet asphalt, steam from vents, moody urban blues and purples', imageUrl: 'https://images.pexels.com/photos/3035151/pexels-photo-3035151.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Ancient Desert 4D', category: '4d', value: '4D Ancient Desert, shifting sand dunes, heat haze distortion, towering pyramids, dusty atmosphere, intense golden sunlight', imageUrl: 'https://images.pexels.com/photos/207529/pexels-photo-207529.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Glitch World 4D', category: '4d', value: '4D Glitch World, digital artifacts, reality tearing, neon static, surreal environments, high-energy glitch motion', imageUrl: 'https://images.pexels.com/photos/5794711/pexels-photo-5794711.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Autumn Leaves 4D', category: '4d', value: '4D Autumn, swirling leaves in wind, warm orange glow, crisp morning air, soft sunlight filtering through branches', imageUrl: 'https://images.pexels.com/photos/7848995/pexels-photo-7848995.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Deep Space Station 4D', category: '4d', value: '4D Space Station, zero gravity floating objects, high-tech monitors, view of distant planets, sterile industrial lighting', imageUrl: 'https://images.pexels.com/photos/2526105/pexels-photo-2526105.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Sakura Petals 4D', category: '4d', value: '4D Sakura, falling cherry blossoms, soft pink lighting, gentle spring breeze, peaceful traditional Japanese setting', imageUrl: 'https://images.pexels.com/photos/3762299/pexels-photo-3762299.jpeg?auto=compress&cs=tinysrgb&w=150' },

  // --- 3D STYLE (10 Styles) ---
  { name: 'Pixar Cinematic', category: '3d', value: 'Pixar-style 3D animation, cinematic lighting, cute and expressive characters, high fidelity, 8k, octane render', imageUrl: 'https://images.pexels.com/photos/7848995/pexels-photo-7848995.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Disney Whimsical', category: '3d', value: 'Disney-style 3D animation, magical atmosphere, intermediate textures, bright colors, heartwarming characters, fairytale lighting', imageUrl: 'https://images.pexels.com/photos/289998/pexels-photo-289998.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Unreal Engine 5', category: '3d', value: 'Unreal Engine 5 cinematic render, photorealistic lighting, Nanite detail level, high-end production look', imageUrl: 'https://images.pexels.com/photos/2526105/pexels-photo-2526105.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Claymation', category: '3d', value: 'Claymation style, stop-motion animation, handcrafted plasticine texture, thumbprint details, Aardman style', imageUrl: 'https://images.pexels.com/photos/385997/pexels-photo-385997.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Low-Poly Game Art', category: '3d', value: 'Low-poly 3D style, geometric shapes, flat shading, minimalist retro game look, clean and stylish', imageUrl: 'https://images.pexels.com/photos/3797931/pexels-photo-3797931.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Toybox Pastel', category: '3d', value: '3D cartoon, toybox pastel aesthetic, soft colors, rounded shapes, gentle lighting, baby-friendly', imageUrl: 'https://images.pexels.com/photos/1036396/pexels-photo-1036396.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Voxel Art', category: '3d', value: '3D Voxel art, Minecraft aesthetic, blocky world, vibrant colors, 3D pixel grid', imageUrl: 'https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'DreamWorks Style', category: '3d', value: 'DreamWorks-style 3D, high energy action, detailed textures, expressive faces, cinematic movie look', imageUrl: 'https://images.pexels.com/photos/7848995/pexels-photo-7848995.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Octane Render Glow', category: '3d', value: '3D render with Octane lighting, neon glow, reflective surfaces, volumetric fog, digital art masterpiece', imageUrl: 'https://images.pexels.com/photos/2526105/pexels-photo-2526105.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Soft Plushie 3D', category: '3d', value: '3D render, ultra-soft furry textures, plushie character look, soft warm lighting, adorable animal feel', imageUrl: 'https://images.pexels.com/photos/4587955/pexels-photo-4587955.jpeg?auto=compress&cs=tinysrgb&w=100' },

  // --- ANIME (10 Styles) ---
  { name: 'Studio Ghibli', category: 'anime', value: 'Studio Ghibli style, hand-drawn aesthetic, lush natural landscapes, heartwarming whimsy, watercolor sky', imageUrl: 'https://images.pexels.com/photos/3762299/pexels-photo-3762299.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Makoto Shinkai', category: 'anime', value: 'Makoto Shinkai style, atmospheric depth, vibrant colors, lens flares, photorealistic anime environments', imageUrl: 'https://images.pexels.com/photos/1906658/pexels-photo-1906658.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: '90s Retro Anime', category: 'anime', value: 'Retro 90s anime style, nostalgic grain, soft pastel colors, cel-shaded animation look, classic Sailor Moon vibe', imageUrl: 'https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Modern Shonen', category: 'anime', value: 'Modern shonen action style, dynamic poses, high-contrast lighting, bold line art, high-energy impact frames', imageUrl: 'https://images.pexels.com/photos/2526105/pexels-photo-2526105.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Cyberpunk Anime', category: 'anime', value: 'Cyberpunk anime style, neon cityscapes, futuristic technology, high contrast red and blue, Ghost in the Shell vibe', imageUrl: 'https://images.pexels.com/photos/5794711/pexels-photo-5794711.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Chibi / Kawaii', category: 'anime', value: 'Chibi anime style, cute small characters, large expressive heads, simple bright colors, Kawaii aesthetic', imageUrl: 'https://images.pexels.com/photos/4587955/pexels-photo-4587955.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Ukiyo-e Anime', category: 'anime', value: 'Traditional Japanese woodblock style anime, stylized waves and clouds, flat muted colors, high-detail line art', imageUrl: 'https://images.pexels.com/photos/3762299/pexels-photo-3762299.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Dark Gothic Anime', category: 'anime', value: 'Dark gothic anime, heavy black shadows, Victorian elements, mysterious atmosphere, sharp sharp character features', imageUrl: 'https://images.pexels.com/photos/5794711/pexels-photo-5794711.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Futuristic Mecha', category: 'anime', value: 'Mecha anime style, complex mechanical parts, blue glowing panels, high-tech industrial setting', imageUrl: 'https://images.pexels.com/photos/2526105/pexels-photo-2526105.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Watercolor Shojo', category: 'anime', value: 'Shojo anime style, watercolor textures, flower petals in the air, soft sparkling eyes, romantic light', imageUrl: 'https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg?auto=compress&cs=tinysrgb&w=100' },

  // --- 2D STYLE (10 Styles) ---
  { name: 'Flat Vector Illustration', category: '2d', value: '2D flat vector art, bold solid colors, geometric shapes, modern corporate design style', imageUrl: 'https://images.pexels.com/photos/159751/book-address-book-learning-learn-159751.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Paper Cutout', category: '2d', value: '2D paper cutout style, layered depth, visible paper edges and textures, drop shadows, vibrant colors', imageUrl: 'https://images.pexels.com/photos/673648/pexels-photo-673648.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Pop Art', category: '2d', value: 'Pop art style, Roy Lichtenstein inspired, halftone dots, primary colors, bold black outlines, comic book feel', imageUrl: 'https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Hand-Drawn Sketch', category: '2d', value: '2D hand-drawn pencil sketch, rough graphite textures, graphite shading, artistic and traditional feel', imageUrl: 'https://images.pexels.com/photos/385997/pexels-photo-385997.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Minimalist Line Art', category: '2d', value: '2D minimalist line art, single continuous line style, elegant simplicity, clean white background', imageUrl: 'https://images.pexels.com/photos/3797931/pexels-photo-3797931.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Chalkboard Drawing', category: '2d', value: 'White chalk on black chalkboard, dusty texture, hand-drawn diagrams and illustrations', imageUrl: 'https://images.pexels.com/photos/159751/book-address-book-learning-learn-159751.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Infographic Style', category: '2d', value: 'Professional infographic 2D design, clean icons, organized layout, instructive and modern', imageUrl: 'https://images.pexels.com/photos/159751/book-address-book-learning-learn-159751.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Vintage Newspaper', category: '2d', value: 'Old newspaper comic style, halftone print, aged yellow paper, ink bleeds, nostalgic 20th century look', imageUrl: 'https://images.pexels.com/photos/385997/pexels-photo-385997.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Oil Painting 2D', category: '2d', value: 'Impressionist oil painting, visible thick brushstrokes, rich color blending, canvas texture', imageUrl: 'https://images.pexels.com/photos/3797931/pexels-photo-3797931.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: '8-Bit Pixel Art', category: '2d', value: 'Retro 8-bit pixel art, low resolution grid, limited color palette, early video game console aesthetic', imageUrl: 'https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=100' },

  // --- ROBLOX STYLE (10 Styles) ---
  { name: 'Classic Blocky', category: 'roblox', value: 'Roblox blocky character, simple geometric shapes, vibrant plastic textures, 3D game aesthetic', imageUrl: 'https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Tactical Roblox', category: 'roblox', value: 'Roblox military avatar, detailed tactical gear, vests, pouches, gritty combat lighting, 3D environment', imageUrl: 'https://images.pexels.com/photos/3035151/pexels-photo-3035151.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Preppy Blox', category: 'roblox', value: 'Roblox preppy style, soft colors, trendy outfits, cute accessories, bright high-key lighting', imageUrl: 'https://images.pexels.com/photos/4587955/pexels-photo-4587955.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Cyber Blox', category: 'roblox', value: 'Roblox futuristic cyberpunk style, glowing neon parts, holographic accessories, dark high-contrast lighting', imageUrl: 'https://images.pexels.com/photos/2526105/pexels-photo-2526105.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Fantasy Blox', category: 'roblox', value: 'Roblox RPG style, magic armor, glowing swords, fantasy realm background, epic 3D adventure look', imageUrl: 'https://images.pexels.com/photos/289998/pexels-photo-289998.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Luxury Blox', category: 'roblox', value: 'Roblox high-end fashion, glossy suits and dresses, designer accessories, premium studio lighting', imageUrl: 'https://images.pexels.com/photos/1036396/pexels-photo-1036396.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Survival Blox', category: 'roblox', value: 'Roblox survival style, rugged gear, forest or post-apocalyptic setting, natural atmospheric lighting', imageUrl: 'https://images.pexels.com/photos/3762299/pexels-photo-3762299.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Meme Blox', category: 'roblox', value: 'Funny Roblox characters, exaggerated proportions, silly faces, bright comical environment', imageUrl: 'https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Sports Blox', category: 'roblox', value: 'Roblox athlete style, sports jersey, dynamic action pose, stadium background, high energy', imageUrl: 'https://images.pexels.com/photos/207529/pexels-photo-207529.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Dark Blox', category: 'roblox', value: 'Roblox edgy style, all-black clothing, chains, moody dark environment, dramatic shadow lighting', imageUrl: 'https://images.pexels.com/photos/5794711/pexels-photo-5794711.jpeg?auto=compress&cs=tinysrgb&w=150' },

  // --- STICKMAN STYLE (10 Styles) ---
  { name: 'Minimalist Stick', category: 'stickman', value: 'Minimalist stickman drawing, simple black lines on white background, basic emotional expressions', imageUrl: 'https://images.pexels.com/photos/3797931/pexels-photo-3797931.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Action Stickman', category: 'stickman', value: 'Dynamic stickman action, motion lines, high-energy fighting poses, epic combat perspective', imageUrl: 'https://images.pexels.com/photos/207529/pexels-photo-207529.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Crayon Stickman', category: 'stickman', value: 'Child-like stickman drawing, crayon textures, rough wax strokes, colorful and playful', imageUrl: 'https://images.pexels.com/photos/385997/pexels-photo-385997.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Glowing Neon Stick', category: 'stickman', value: 'Glow-in-the-dark neon stickman, bright cyan and magenta light lines, dark pitch-black background', imageUrl: 'https://images.pexels.com/photos/2526105/pexels-photo-2526105.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: '3D Plastic Stick', category: 'stickman', value: '3D rendered stickman, high-gloss plastic material, soft studio lighting, modern minimalist look', imageUrl: 'https://images.pexels.com/photos/1036396/pexels-photo-1036396.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Comic Book Stick', category: 'stickman', value: 'Stickman in a 2D comic book style, action bubbles, halftone backgrounds, bold speed lines', imageUrl: 'https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Watercolor Stickman', category: 'stickman', value: 'Artistic watercolor stickman, bleeding edges, soft pigments, artistic paper texture background', imageUrl: 'https://images.pexels.com/photos/3797931/pexels-photo-3797931.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Gothic Dark Stick', category: 'stickman', value: 'Dark gothic stickman, scratchy ink textures, deep shadows, macabre atmosphere', imageUrl: 'https://images.pexels.com/photos/5794711/pexels-photo-5794711.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Paper Cut Stick', category: 'stickman', value: 'Stickman as paper cutout, physical layered look, shadow depth, handcrafted feel', imageUrl: 'https://images.pexels.com/photos/673648/pexels-photo-673648.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Tech / HUD Stick', category: 'stickman', value: 'Futuristic digital stickman, data lines, HUD elements, blue digital glow, sci-fi computer interface aesthetic', imageUrl: 'https://images.pexels.com/photos/2526105/pexels-photo-2526105.jpeg?auto=compress&cs=tinysrgb&w=150' },

  // --- FANTASY STYLE (10 Styles) ---
  { name: 'Mythological Painting', category: 'fantasy', value: 'Ancient mythological oil painting style, dramatic chiaroscuro lighting, epic historical fantasy, museum quality, intricate brushwork', imageUrl: 'https://images.pexels.com/photos/289998/pexels-photo-289998.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Realistic Cinematic', category: 'fantasy', value: 'Realistic cinematic, high dynamic range, film-like color grading, epic atmosphere, professional lighting setup', imageUrl: 'https://images.pexels.com/photos/3035151/pexels-photo-3035151.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Cinematic Fantasy Pro', category: 'fantasy', value: 'Ultra-realistic cinematic fantasy, complex world-building, magical ambiance, 8k resolution, volumetric lighting, epic scale', imageUrl: 'https://images.pexels.com/photos/2526105/pexels-photo-2526105.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Hyper-Real Fantasy', category: 'fantasy', value: 'Hyper-realism fantasy style, intricate textures, lifelike skin and materials, high-fidelity render, octane render, extremely detailed', imageUrl: 'https://images.pexels.com/photos/7848995/pexels-photo-7848995.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Ethereal Dreamscape', category: 'fantasy', value: 'Soft ethereal dreamscape, glowing particles, magical ambiance, pastel magical colors, floating elements, fantasy concept art, mystical', imageUrl: 'https://images.pexels.com/photos/289998/pexels-photo-289998.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Dark High Fantasy', category: 'fantasy', value: 'Gritty dark high fantasy, gothic architecture, ominous atmosphere, deep shadows, crimson and black tones, realistic textures, terrifying', imageUrl: 'https://images.pexels.com/photos/5794711/pexels-photo-5794711.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Enchanted Forest Nature', category: 'fantasy', value: 'Photorealistic enchanted forest, bioluminescent plants, magical creatures hidden in shadows, macro nature details, 8k, vibrant moss', imageUrl: 'https://images.pexels.com/photos/3762299/pexels-photo-3762299.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Steampunk Fantasy', category: 'fantasy', value: 'Steampunk fantasy hybrid, mechanical brass details, steam-powered magic, Victorian aesthetic, complex gear structures, realistic metals, industrial', imageUrl: 'https://images.pexels.com/photos/2526105/pexels-photo-2526105.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Crystal Kingdom Realism', category: 'fantasy', value: 'Crystal kingdom realism, translucent crystalline structures, refracted light, prismatic colors, sharp geometric fantasy, high-gloss finish', imageUrl: 'https://images.pexels.com/photos/1193743/pexels-photo-1193743.jpeg?auto=compress&cs=tinysrgb&w=150' },
  { name: 'Celestial Voyage', category: 'fantasy', value: 'Celestial fantasy, cosmic nebula clouds, star-lit environments, divine structures, epic universe scale, glowing constellations', imageUrl: 'https://images.pexels.com/photos/207529/pexels-photo-207529.jpeg?auto=compress&cs=tinysrgb&w=150' },
];
